### ISSUE TITLE
로봇이 접근할때 사용자가 원하는 페이지또는 act에서만 접근가능하도록 하면 좋겠습니다.

### ISSUE THREAD

**Issue by bjrambo** [kijin/xe-sitemaplite#1]
무슨이유인지 모르겠지만 코노리님의 [소셜XE](https://www.xetown.com/index.php?&mid=xepoint&search_keyword=%EC%86%8C%EC%85%9C&search_target=title_content&document_srl=2930)에서 많은 네이버 웹마스터 오류가 검출되는 상황인데요.
사이트 맵에서 전체적인 f로봇이 접근할수있는 규칙이나 그런것들을 robot.txt파일같은 것을 제작할 수 있는 항목이 있으면 어떨까요?

**Comment by kijin** [comment]
기본적으로 메인 메뉴(GNB)에 포함되어 있는 주소만 사이트맵에 포함됩니다. 그 밖의 개별 페이지는 포함되지 않습니다. 소셜로그인 페이지를 메뉴에 포함시키지 않았다면 사이트맵에서도 당연히 제외됩니다.

robots.txt는 직접 작성하세요.

**Comment by bjrambo** [comment]
@kijin 사실.. robots.txt에 익숙하지 않은 사용자가 많다고 생각해요.
직접 작성하더라도 재대로된 XE용 예시가 없는게 사실이죠..

그래서 모듈내에서 가이드라던지..그런걸 제안해둔거에요. 

아무리 직접적으로 운영하시는 분들이라도 해도 @wookho 님같이 전체적인 검색엔진에 대한 재대로아는 분들이 많이 없다고 생각해요.

지금이야 XE에 대해서 @wookho 님이나 많은분들이 공유해줘서 알지만.. 전체 XE사용자중에 그래도 일부라고 생각해요.

사실 사이트 운영하시는 분들이라면 XETown을 많이 알거나 공홈에서 정보를 재대로 얻으시는 분 많이 없다고 생각해요. 이를 공홈에 올리시거나 쉬운설치에 노출될 수 있는 모듈이라면 이 항목까지 전체적으로 잡아주는게 어떨까하는게 제 생각이에요.

**Comment by bjrambo** [comment]
사실 사이트 맵이지만... 전체적인 로봇 방문을 도울수있는 모듈이기 때문에 robots.txt에 대한 의견을 제시한거엿어요.

**Comment by kijin** [comment]
제대로 된 로봇이라면 사이트맵이 필요하지도 않죠 ㅋㅋ

여기는 사이트맵 모듈이니, 로봇 관련 기능은 SEO나 그 밖의 다른 모듈에서 처리하면 좋을 것 같아요.

**Comment by bjrambo** [comment]
사실...
XE내에서 재대로된 SEO모듈은 없다고 생각해요..
공홈의 SEO나...COnory님이 제작하신 SEO나..(죄송해요 ㅠㅠ)
저는 SEO라면.. 전체적인 검색엔진에 도움이 줬으면 좋겠는데 그게 안되어서.. 전반적인 로봇을 컨트롤 하는 그런 모듈이 될수 잇으면 좋지 않을까 라는 생각을 한번 해봤어요.
ㅠ.ㅠ

**Comment by kijin** [comment]
13e1c69 에서 회원모듈(로그인, 비번찾기 등)과 소셜XE(dispSocialxeConnectSns 등) URL도 제외시키도록 하였습니다. 메뉴에 종종 포함되어 있지만 사이트맵에서는 필요하지 않으니까요.

**Comment by kijin** [comment]
5980474 에서 로그인 사용자 전용 / 관리자 전용 / 그룹에 따라 접근이 제한된 메뉴는 사이트맵에서 제외하는 옵션을 추가했습니다.

**Comment by bjrambo** [comment]
:+1:
