### ISSUE TITLE
꼭 문서가 아니라도 노출되었으면 좋겠습니다.

### ISSUE THREAD

**Issue by bjrambo** [kijin/xe-sitemaplite#2]
document 모듈을 이용하게 되면 insert시 많은 로직이 많이 노출됩니다.

예를 들어 인스타그램 모듈에서 insert시, document 로직을 이용하게되면,
gginstagram.controller.php 에 있는 insertInstagramDB 메소드에서 실행한 Document 옵션에 따라 insert하게됨과 동시에 before insertDocument, after insertDocument 트리거가 실행되고 거기에 맞물린 알림센터 트리거라던지 등등이 실행됨으로써 느리게 되는경우가 많아요. 그래서 트리거 보다는 일반 디비를 선택하는 경우가 많이 생겨버렷어요.

하지만, 그래도 이러한 내용들을 같이 노출할 수 있는 형태가 되면 어떨까요?

**Comment by bjrambo** [comment]
물론 좀 선택적인 제한이 있으면 좋겠어요.

**Comment by kijin** [comment]
모듈 설명을 다시 읽어보세요. 이 모듈은 문서가 노출되지 않습니다 ^^

**Comment by bjrambo** [comment]
@_@?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by kijin** [comment]
최신 커밋 기준으로 확인해 보시면 아마 좀더 기능이 좋아졌을 거예요 ^^
