### ISSUE TITLE
http://www.sitemaps.org/schemas/sitemap/0.9 를 선언하지 않습니다.

### ISSUE THREAD

**Issue by jominhyun** [kijin/xe-sitemaplite#3]
구글에 사이트맵을 제출하면

http://www.sitemaps.org/schemas/sitemap/0.9 를 선언하지 않습니다.

라는 문구가 나타납니다.

그런데, 이 모듈은 메뉴만 등록되고, 게시물갯수는 잡히지 않는데,
공홈에 올라온 sitemap모듈을 뺴고 이것만 사용해도 비슷한 효과가 있을까요

**Comment by kijin** [comment]
8bd0cb7 에서 수정되었습니다. 설정을 다시 한 번 저장해 주시기 바랍니다.

사이트맵에 굳이 모든 게시물을 나열하지 않아도 게시판 주소만 알려주면 알아서 크롤링해갈 것이라고 가정하고 만든 모듈입니다. 사실 구글은 사이트맵 따위가 없어도 알아서 잘 긁어가기만 하지요. 네이버가 문제인데, 그쪽은 도무지 어떻게 작동하는지 알 수가 없으니...

**Comment by jominhyun** [comment]
@kijin 넵 감사합니다 적용해보겠습니다
