### ISSUE TITLE
메뉴접근권한에 따른 (선택적) 제한기능

### ISSUE THREAD

**Issue by realgood253** [kijin/xe-sitemaplite#4]
현재 sitemaplite모듈은 
XE(rhymix)의 사이트맵들중 모듈설정에 따라 선택된 사이트맵(들)에 속해있는 메뉴들에 대해서 자동적으로 sitemap.xml 파일을 만들고 XE메뉴구성이 변경시 자동으로 sitemap.xml을 갱신합니다.

사이트맵에 속해있는 메뉴들 중 '로그인한 회원에게만' 표시가 되거나 열람이 가능할 경우에는
기본적으로 검색봇이 정상적인 크롤링 불가능한 상태이고,
혹은 민감한 정보거나 사이트운영자가 검색을 원치 않는 경우가 있을수도 있다고 생각됩니다.
(robots.txt 로 크롤링을 거부했는데, sitemap.xml에서는 해당 메뉴를 또 알려주게되는...)

수작업으로 sitemap.xml을 수정할수도 있지만, 메뉴가 변경될때마다 자동갱신되는 모듈 특성도 있고,
또, (열람만 금지됐을 경우)게시물의 제목부분만이라도 크롤링해가는걸 원하는 운영자가 있을수도 있으므로.. 
메뉴접근권한에 따라 사이트맵에 노출할지를 선택할 수 있는 옵션으로 넣으면 어떨까합니다.
어떤식으로 선택하도록 하는게 가장 좋을지는 저로서는 잘 떠오르지 않지만.......

p.s (기진곰님 명령에 따라ㅠ) 처음 이슈등록을 해보는거라.. 제대로 했는지 모르겠네요..

**Comment by kijin** [comment]
헤헤~ 기다리고 있었습니다.

지금 깃허브에서 다운로드 받아서 써보시면 "공개된 메뉴만 포함"이라는 옵션이 추가되었을 거예요. 전체공개가 아닌 메뉴를 제외해 주는 옵션입니다.

**Comment by realgood253** [comment]
바로 적용하도록 하겠습니다!
