### ISSUE TITLE
RSS 제출기능같은것도 가능할까요?

### ISSUE THREAD

**Issue by realgood253** [kijin/xe-sitemaplite#5]
XE(Rhymix)에서 제공하는 통합RSS 를 ping을 때려서 제출하는 기능은 어떨까해서요.

sitemaplite 모듈 1.0 버전에서 '메뉴에 대한 사이트맵'으로 간단하게 제작되었을때
신규문서에 대한 부분은 RSS 제출로 가능하지 않을까라고 생각했었습니다.
(RSS로 조절하면 메뉴에 따라 공개/비공개, 전문/요약 등의 설정도 따로 가능한거 같았고요.)

1.0.1 에서 문서들에 대해서도 일부 사이트맵 제작이 가능해져서 어떤 방법이 노출에 더 효율적일지는 잘 모르겠지만..
RSS 제출로는 신규문서들을
sitemaplite모듈에서는 조회수나,추천수에 따라서 
좀 더 상위노출이 가능한 문서들만 봇에게 알려주는 형식도 가능하지 않을까하는 생각이 들었습니다.

다만, 구글웹마스터등에 운영자가 직접 RSS등록하면 되는 부분이기도 하고.. 
변경시마다(혹은 일정기간마다) ping을 때려서 강제로 알리는게 과연 효과가 있는지는 
제가 SEO 부분에 아는게 없어서 잘 모르겠지만...  그냥 아이디어쯤으로 생각해주시면....

p.s 모듈명이 sitemap'lite'라 가볍게 사이트맵만 제작하는 기능을 담으시려고 했던거 같은.....

**Comment by kijin** [comment]
이미 코어에 RSS 모듈이 포함되어 있고, 말씀하신 것처럼 직접 등록하면 되기 때문에 사이트맵 Lite 모듈 쪽에서 별도로 ping을 넣어줄 필요는 없을 것 같습니다. ping을 넣는다고 검색엔진에서 즉시 크롤링하는 것도 아니고, 검색엔진에게는 전문/요약 구분도 의미가 없죠.

**Comment by realgood253** [comment]
그렇겠네요. 어차피 와서 긁어가야하니까 전문이든 요약이든! ㅋ
