### ISSUE TITLE
네이버 오류

### ISSUE THREAD

**Issue by jominhyun** [kijin/xe-sitemaplite#6]
네이버 사이트맵 제출시

사이트맵의 마지막라인에 문제가있다는 문구나타납니다

---

구글사이트맵 제출 후

잘못된 URL입니다.
유효한 URL이 아닙니다. 수정한 후 다시 제출하십시오.
1
상위 태그: url
태그: loc

---

**Comment by kijin** [comment]
문제가 있는 사이트맵의 주소를 알려주시기 바랍니다.

**Comment by jominhyun** [comment]
@kijin 방금전에 다시 사이트맵을 제출했더니 오류없이 등록이됩니다.
희안하네요... 어제만하더라도 계속 등록거부가 나타났는데 ㅜㅜ
제 머리 상태가 이상한건지... 네이버웹마스터가 이상한건지...

**Comment by kijin** [comment]
예전에 쓰시던 다른 사이트맵을 네이버가 기억하고 있었는지도 몰라요.
